{{ doctype() | raw }}

<html lang="en">
    <head>
        <base href="/" />
        <meta charset="utf-8">

        {{ headTitle() | raw }}
        {{ headMeta() | raw }}

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
            {{ placeholder('html5js') | raw }}
        <![endif]-->

        {{ headScript() | raw }}

        <!-- Le styles -->
        {{ headLink() | raw }}

        <style type="text/css">
          body {
            padding-top: 60px;
          }
        </style>
    
        <!-- Le fav and touch icons -->
        {{ placeholder('favicon') | raw }}

  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="{{ url('home') }}">ZF2 Skeleton Application</a>

          <ul class="nav">
            <li class="active"><a href="{{ url('home') }}">Home</a></li>
          </ul>
        </div>
      </div>

    </div>

    <div class="container">
      {{content | raw}}
      <footer>
        <p>&copy; 2006 - {{ date('Y') }} by ZendExperts. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
