<?php echo $this->doctype('XHTML11') ?>

<html lang="en">
    <head>
        <base href="/" />
        <meta charset="utf-8" content="text/html" />
        <?php echo $this->headTitle() ?>

        <?php echo $this->headMeta() ?>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="/js/html5.js" type="text/javascript"></script>
        <![endif]-->
        <?php echo $this->headScript() ?>

        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/css/default.css" />
        <?php echo $this->headLink() ?>

    </head>

    <body>

        <div class="topbar">
            <div class="fill">
                <div class="container">
                    <a class="brand" href="<?php echo $this->url('home') ?>">ProjectQuery</a>
                    <ul class="nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                        <li><a href="<?php echo $this->url('ze_auth') ?>">Login</a></li>
                    </ul>
                </div>
            </div>
        </div> <!-- /topbar -->


        <div class="container">
            <?php echo $this->raw('content'); ?>

            <footer>
                <p>&copy; 2006 - <?php echo date('Y') ?> by Around25 Srl. All rights reserved.</p>
            </footer>
        </div> <!-- /container -->

    </body>
</html>
